// 图标组件索引文件
export { default as IconNewFile } from './1IconNewFile.vue'
export { default as IconOpenFolder } from './2IconOpenFolder.vue'
export { default as IconSave } from './3IconSave.vue'
export { default as IconPrint } from './4IconPrint.vue'
export { default as IconSearch } from './5IconSearch.vue'
export { default as IconZoomIn } from './6IconZoomIn.vue'
export { default as IconZoomOut } from './7IconZoomOut.vue'
export { default as IconFitToScreen } from './8IconFitToScreen.vue'
export { default as IconDrag } from './9IconDrag.vue'
export { default as IconArrowUp } from './10IconArrowUp.vue'
export { default as IconArrowRight } from './11IconArrowRight.vue'
export { default as IconNorthPole } from './12IconNorthPole.vue'
export { default as IconCompass } from './13IconCompass.vue'
export { default as IconBreak } from './14IconBreak.vue'
export { default as IconDiscrete } from './15IconDiscrete.vue'
export {default as IconLength} from './16IconLength.vue'
export {default as IconTuoPu} from './17IconTuoPu.vue'
export {default as IconAnTiTuoPu} from './18IconAnTiTuoPu.vue'
export { default as IconHeatmapEarth } from './19IconHeatmapEarth.vue'
export { default as IconLatLonEarth } from './20IconLatLonEarth.vue'
export { default as IconGridEarth } from './21IconGridEarth.vue'
export { default as IconAngleMeasurement } from './22IconAngleMeasurement.vue'
export { default as IconSlopeMeasurement } from './23IconSlopeMeasurement.vue'
export { default as IconCone } from './24IconCone.vue'
export { default as IconExclude } from './25IconExclude.vue'
export { default as IconAddText } from './26IconAddText.vue'
export { default as IconSitArrow } from './27IconSitArrow.vue'
export { default as IconOvalBox } from './28IconOvalBox.vue'
export { default as IconRactagle } from './29IconRactagle.vue'

export { default as IconSlash } from './30IconSlash.vue'
export { default as IconIncompleteHexagon } from './31IconIncompleteHexagon.vue'
export { default as IconRegularHexagon } from './32IconRegularHexagon.vue'

// 原有的图标组件
export { default as IconCommunity } from './IconCommunity.vue'
export { default as IconDocumentation } from './IconDocumentation.vue'
export { default as IconEcosystem } from './IconEcosystem.vue'
export { default as IconSupport } from './IconSupport.vue'
export { default as IconTooling } from './IconTooling.vue'
